"""Update schema for checkin pipeline

Revision ID: 58462976bf1c
Revises: 65f0e938c49e
Create Date: 2026-06-09 23:48:40.617526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '58462976bf1c'
down_revision: Union[str, None] = '65f0e938c49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('observations', sa.JSON(), nullable=False))
    op.add_column('checkins', sa.Column('env_data_source', sa.String(length=50), nullable=True))
    op.add_column('checkins', sa.Column('model_version', sa.String(length=100), nullable=True))
    op.add_column('checkins', sa.Column('inference_ms', sa.Integer(), nullable=True))
    op.add_column('checkins', sa.Column('image_hash', sa.String(length=64), nullable=True))
    op.add_column('checkins', sa.Column('lat_rounded', sa.Float(), nullable=True))
    op.add_column('checkins', sa.Column('lng_rounded', sa.Float(), nullable=True))
    op.add_column('lesion_detections', sa.Column('bbox_x', sa.Float(), nullable=False))
    op.add_column('lesion_detections', sa.Column('bbox_y', sa.Float(), nullable=False))
    op.add_column('lesion_detections', sa.Column('bbox_w', sa.Float(), nullable=False))
    op.add_column('lesion_detections', sa.Column('bbox_h', sa.Float(), nullable=False))
    op.add_column('lesion_detections', sa.Column('low_conf', sa.Boolean(), nullable=True))
    op.drop_column('lesion_detections', 'y')
    op.drop_column('lesion_detections', 'x')
    op.drop_column('lesion_detections', 'width')
    op.drop_column('lesion_detections', 'height')
    op.add_column('questionnaire_responses', sa.Column('cnn_p_dry', sa.Float(), nullable=True))
    op.add_column('questionnaire_responses', sa.Column('cnn_p_balanced', sa.Float(), nullable=True))
    op.add_column('questionnaire_responses', sa.Column('cnn_p_oily', sa.Float(), nullable=True))
    op.add_column('questionnaire_responses', sa.Column('fused_p_dry', sa.Float(), nullable=True))
    op.add_column('questionnaire_responses', sa.Column('fused_p_balanced', sa.Float(), nullable=True))
    op.add_column('questionnaire_responses', sa.Column('fused_p_oily', sa.Float(), nullable=True))
    op.add_column('questionnaire_responses', sa.Column('predicted_label', sa.String(length=50), nullable=True))
    op.add_column('questionnaire_responses', sa.Column('signal_source', sa.String(length=50), nullable=True))
    op.add_column('questionnaire_responses', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaire_responses', 'is_active')
    op.drop_column('questionnaire_responses', 'signal_source')
    op.drop_column('questionnaire_responses', 'predicted_label')
    op.drop_column('questionnaire_responses', 'fused_p_oily')
    op.drop_column('questionnaire_responses', 'fused_p_balanced')
    op.drop_column('questionnaire_responses', 'fused_p_dry')
    op.drop_column('questionnaire_responses', 'cnn_p_oily')
    op.drop_column('questionnaire_responses', 'cnn_p_balanced')
    op.drop_column('questionnaire_responses', 'cnn_p_dry')
    op.add_column('lesion_detections', sa.Column('height', mysql.FLOAT(), nullable=False))
    op.add_column('lesion_detections', sa.Column('width', mysql.FLOAT(), nullable=False))
    op.add_column('lesion_detections', sa.Column('x', mysql.FLOAT(), nullable=False))
    op.add_column('lesion_detections', sa.Column('y', mysql.FLOAT(), nullable=False))
    op.drop_column('lesion_detections', 'low_conf')
    op.drop_column('lesion_detections', 'bbox_h')
    op.drop_column('lesion_detections', 'bbox_w')
    op.drop_column('lesion_detections', 'bbox_y')
    op.drop_column('lesion_detections', 'bbox_x')
    op.drop_column('checkins', 'lng_rounded')
    op.drop_column('checkins', 'lat_rounded')
    op.drop_column('checkins', 'image_hash')
    op.drop_column('checkins', 'inference_ms')
    op.drop_column('checkins', 'model_version')
    op.drop_column('checkins', 'env_data_source')
    op.drop_column('checkins', 'observations')
    # ### end Alembic commands ###
